name: Publish

on:
  push:
    branches:   
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  compile:
    name: dart compile exe
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            binary-name: server_linux_amd64
            dart-file-name: server.dart
            os: linux

          - runs-on: ubuntu-latest
            binary-name: client_linux_amd64
            dart-file-name: client.dart
            os: linux

          - runs-on: macos-latest
            binary-name: server_macos_amd64
            dart-file-name: server.dart
            os: macos

          - runs-on: macos-latest
            binary-name: client_macos_amd64
            dart-file-name: client.dart
            os: macos

          - runs-on: windows-latest
            binary-name: server_windows.exe
            dart-file-name: server.dart
            os: windows

          - runs-on: windows-latest
            binary-name: client_windows.exe
            dart-file-name: client.dart
            os: windows


    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: mkdir ${{ matrix.os }}
      - run: dart compile exe ${{ matrix.dart-file-name }} -o  ${{ matrix.os }}/${{ matrix.binary-name }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.binary-name }}
          path: ${{ matrix.os }}




  release:
    needs: compile
    name: github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: server_linux_amd64
          path: linux
      - uses: actions/download-artifact@v2
        with:
            name: client_linux_amd64
            path: linux

      - uses: actions/download-artifact@v2
        with:
          name: server_macos_amd64
          path: macos
      - uses: actions/download-artifact@v2
        with:
            name: client_macos_amd64
            path: macos

      - uses: actions/download-artifact@v2
        with:
            name: server_windows.exe
            path: windows
      - uses: actions/download-artifact@v2
        with:
            name: client_windows.exe
            path: windows

      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: linux|macos|windows/*
