name: Publish

on:
  push:
    branches:   
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  compile:
    name: dart compile exe server
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-latest
            binary-name1: server_linux_amd64
            binary-name2: client_linux_amd64
            dart-file-name1: server.dart
            dart-file-name2: client.dart

          - runs-on: macos-latest
            binary-name1: server_macos_amd64
            binary-name2: client_macos_amd64
            dart-file-name1: server.dart
            dart-file-name2: client.dart

          - runs-on: windows-latest
            binary-name1: server_windows.exe
            binary-name2: client_windows.exe
            dart-file-name1: server.dart
            dart-file-name2: client.dart

    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - run: dart pub get
      - run: mkdir ${{ matrix.runs-on }}
      - run: dart compile exe ${{ matrix.dart-file-name1 }} -o ${{ matrix.runs-on }}/${{ matrix.binary-name1 }}
      - run: dart compile exe ${{ matrix.dart-file-name2 }} -o ${{ matrix.runs-on }}/${{ matrix.binary-name2 }}
      - uses: actions/upload-artifact@v2
        with:
          name: bin-${{ matrix.runs-on }}
          path: ${{ matrix.runs-on }}




  release:
    needs: compile
    name: github release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bin-ubuntu-latest
          path: bin-linux
      - uses: actions/download-artifact@v2
        with:
          name: bin-macos-latest
          path: bin-macos
      - uses: actions/download-artifact@v2
        with:
          name: bin-windows-latest
          path: bin-windows
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: bin-*/*
